language: php
php:
- 5.6
- 5.5
- hhvm

before_script:
  - phpenv config-add myconfig.ini
  - composer install --dev

script:
    - bin/phpunit -c app --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
